[package]
name = "alcro"
version = "0.1.0"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "^0"
regex = "^1"
serde = "^1"
serde_derive = "^1"
ws = "^0"
serde_json = "^1"
websocket = "^0"
