[package]
name = "alcro"
version = "0.1.0"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2018"
description = "A library to create desktop apps using rust and modern web technologies"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/Srinivasa314/alcro"

[dependencies]
tempdir = "^0"
regex = "^1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
crossbeam-channel = "^0"
websocket = "^0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0", features = ["winuser"] }

[dev-dependencies]
actix-web = "^1"
actix-rt = "^0"
rust-embed = "^5"
mime_guess = "^2"

[target.'cfg(windows)'.dev-dependencies]
futures = "^0.1"

[target.'cfg(unix)'.dev-dependencies]
futures = "^0"
