[package]
name = "alcro"
version = "0.1.0"
authors = ["Srinivasa <m.srinivasa1234@gmail.com>"]
edition = "2018"
description = "A library to create desktop apps using rust and modern web technologies"

[dependencies]
tempdir = "^0"
regex = "^1"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
crossbeam-channel = "^0"
websocket = "^0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "^0", features = ["winuser"] }
